version: "3"
services:
  web:
    image: nginx:latest
    ports:
      - "8080:80"
    volumes:
      - ./docker-configs/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
  
  php:
    build: ./docker-configs/php
    image: php:7-fpm
    volumes:
      - ./src/:/var/phpapp/

  mysql:
    image: mysql:latest
    container_name: sample_host
    build: ./docker-configs/mysql
    ports:
      - 3306:3306
    volumes:
      - ./docker-configs/mysql/init:/docker-entrypoint-initdb.d
      - ./data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: sample_root_pass
      MYSQL_DATABASE: sample_db
      MYSQL_USER: sample_user
      MYSQL_PASSWORD: sample_pass

  phpmyadmin:
    container_name: sample_db
    image: phpmyadmin/phpmyadmin
    environment:
    - PMA_ARBITRARY=1
    - PMA_HOSTS=sample_host
    - PMA_USER=sample_user
    - PMA_PASSWORD=sample_pass
    ports:
    - 1000:80